// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SeedConfig {
    #[prost(string, tag = "1")]
    pub master_key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub encrypted_key: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub version: u32,
}
impl ::prost::Name for SeedConfig {
    const NAME: &'static str = "SeedConfig";
    const PACKAGE: &'static str = "secret.registration.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "secret.registration.v1beta1.SeedConfig".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/secret.registration.v1beta1.SeedConfig".into()
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LegacySeedConfig {
    #[prost(string, tag = "1")]
    pub master_cert: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub encrypted_key: ::prost::alloc::string::String,
}
impl ::prost::Name for LegacySeedConfig {
    const NAME: &'static str = "LegacySeedConfig";
    const PACKAGE: &'static str = "secret.registration.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "secret.registration.v1beta1.LegacySeedConfig".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/secret.registration.v1beta1.LegacySeedConfig".into()
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegistrationNodeInfo {
    #[prost(bytes = "vec", tag = "1")]
    pub certificate: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub encrypted_seed: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for RegistrationNodeInfo {
    const NAME: &'static str = "RegistrationNodeInfo";
    const PACKAGE: &'static str = "secret.registration.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "secret.registration.v1beta1.RegistrationNodeInfo".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/secret.registration.v1beta1.RegistrationNodeInfo".into()
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RaAuthenticate {
    #[prost(bytes = "vec", tag = "1")]
    pub sender: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub certificate: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for RaAuthenticate {
    const NAME: &'static str = "RaAuthenticate";
    const PACKAGE: &'static str = "secret.registration.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "secret.registration.v1beta1.RaAuthenticate".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/secret.registration.v1beta1.RaAuthenticate".into()
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MasterKey {
    #[prost(bytes = "vec", tag = "1")]
    pub bytes: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for MasterKey {
    const NAME: &'static str = "MasterKey";
    const PACKAGE: &'static str = "secret.registration.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "secret.registration.v1beta1.MasterKey".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/secret.registration.v1beta1.MasterKey".into()
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Key {
    #[prost(bytes = "vec", tag = "1")]
    pub key: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for Key {
    const NAME: &'static str = "Key";
    const PACKAGE: &'static str = "secret.registration.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "secret.registration.v1beta1.Key".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/secret.registration.v1beta1.Key".into()
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GenesisState {
    #[prost(message, repeated, tag = "1")]
    pub registration: ::prost::alloc::vec::Vec<RegistrationNodeInfo>,
    #[prost(message, optional, tag = "2")]
    pub node_exch_master_key: ::core::option::Option<MasterKey>,
    #[prost(message, optional, tag = "3")]
    pub io_master_key: ::core::option::Option<MasterKey>,
}
impl ::prost::Name for GenesisState {
    const NAME: &'static str = "GenesisState";
    const PACKAGE: &'static str = "secret.registration.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "secret.registration.v1beta1.GenesisState".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/secret.registration.v1beta1.GenesisState".into()
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryEncryptedSeedRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub pub_key: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for QueryEncryptedSeedRequest {
    const NAME: &'static str = "QueryEncryptedSeedRequest";
    const PACKAGE: &'static str = "secret.registration.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "secret.registration.v1beta1.QueryEncryptedSeedRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/secret.registration.v1beta1.QueryEncryptedSeedRequest".into()
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryEncryptedSeedResponse {
    /// \[(gogoproto.nullable) = false\];
    #[prost(bytes = "vec", tag = "1")]
    pub encrypted_seed: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for QueryEncryptedSeedResponse {
    const NAME: &'static str = "QueryEncryptedSeedResponse";
    const PACKAGE: &'static str = "secret.registration.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "secret.registration.v1beta1.QueryEncryptedSeedResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/secret.registration.v1beta1.QueryEncryptedSeedResponse".into()
    }
}
/// Generated client implementations.
#[cfg(feature = "grpc")]
pub mod query_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::http::Uri;
    use tonic::codegen::*;
    /// Query provides defines the gRPC querier service
    #[derive(Debug, Clone)]
    pub struct QueryClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    #[cfg(feature = "grpc-transport")]
    impl QueryClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> QueryClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> QueryClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<http::Request<tonic::body::BoxBody>>>::Error:
                Into<StdError> + Send + Sync,
        {
            QueryClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Returns the key used for transactions
        pub async fn tx_key(
            &mut self,
            request: impl tonic::IntoRequest<()>,
        ) -> std::result::Result<tonic::Response<super::Key>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::new(
                    tonic::Code::Unknown,
                    format!("Service was not ready: {}", e.into()),
                )
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/secret.registration.v1beta1.Query/TxKey");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "secret.registration.v1beta1.Query",
                "TxKey",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// Returns the key used for registration
        pub async fn registration_key(
            &mut self,
            request: impl tonic::IntoRequest<()>,
        ) -> std::result::Result<tonic::Response<super::Key>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::new(
                    tonic::Code::Unknown,
                    format!("Service was not ready: {}", e.into()),
                )
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/secret.registration.v1beta1.Query/RegistrationKey",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "secret.registration.v1beta1.Query",
                "RegistrationKey",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// Returns the encrypted seed for a registered node by public key
        pub async fn encrypted_seed(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryEncryptedSeedRequest>,
        ) -> std::result::Result<tonic::Response<super::QueryEncryptedSeedResponse>, tonic::Status>
        {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::new(
                    tonic::Code::Unknown,
                    format!("Service was not ready: {}", e.into()),
                )
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/secret.registration.v1beta1.Query/EncryptedSeed",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "secret.registration.v1beta1.Query",
                "EncryptedSeed",
            ));
            self.inner.unary(req, path, codec).await
        }
    }
}
